export const PIE_COLORS = [
  '#384eaa', // IRIS Blue (primary)
  '#111827', // Black
  '#0891b2', // Cyan (cool, professional)
  '#475569', // Slate Gray
  '#7c3aed', // Deep Purple (royal, sophisticated)
  '#0f766e', // Teal (complements blue)
  '#581c87', // Dark Purple
  '#334155', // Dark Slate
  '#8b5cf6', // Violet (softer purple)
  '#84CC16', // Lime
  '#06B6D4', // Cyan
  '#A855F7', // Violet
]

export const MONTHS = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
]

export const PROJECT_INFO_EXTRA_FIELDS = [
  { column: 'pe_number', label: 'PE #' },
  { column: 'engineer_email', label: 'Engineer Email' },
  { column: 'engineer_phone', label: 'Engineer Phone' },
  { column: 'engineer_date', label: 'Date' },
  { column: 'developer_name', label: 'Developer Name' },
  { column: 'owner_name', label: 'Owner Name' },
  { column: 'corporate_title', label: 'Corporate Title' },
  { column: 'owner_address', label: 'Owner Address' },
  { column: 'owner_number_and_street', label: 'Owner # and Street' },
  { column: 'owner_city_state_zip', label: 'Owner City, State, Zip' },
  { column: 'owner_city_state', label: 'Owner City, State' },
  { column: 'owner_city', label: 'Owner City' },
  { column: 'owner_state', label: 'Owner State' },
  { column: 'owner_zip', label: 'Owner Zip' },
  { column: 'owner_email', label: 'Owner Email' },
  { column: 'owner_phone', label: 'Owner Phone' },
  { column: 'project_address', label: 'Project Address' },
  { column: 'project_ref_number', label: 'Project #' },
  { column: 'project_number_and_street', label: 'Project # and Street' },
  { column: 'project_city_state_zip', label: 'Project City, State, Zip' },
  { column: 'project_street_city_state_zip', label: 'Project Street, City, State, Zip' },
  { column: 'section', label: 'Section' },
  { column: 'township', label: 'Township' },
  { column: 'range', label: 'Range' },
  { column: 'between_streets', label: 'Between Streets' },
  { column: 'council_district', label: 'Council District' },
  { column: 'planning_district', label: 'Planning District' },
  { column: 'census_tract', label: 'Census Tract' },
  { column: 'zoning', label: 'Zoning' },
  { column: 'pud_ordinance', label: 'PUD Ordinance' },
  { column: 'mobility_zone', label: 'Mobility Zone' },
  { column: 'panel_number', label: 'Panel Number' },
  { column: 're_numbers', label: 'RE Numbers' },
  { column: 'transportation_land_use_code', label: 'Transportation Land Use Code' },
  { column: 'previous_land_use_code', label: 'Previous Land Use Code' },
  { column: 'total_land_area', label: 'Total Land Area' },
  { column: 'developed_land_area', label: 'Developed Land Area' },
  { column: 'total_units', label: 'Total Units' },
  { column: 'single_family_units', label: 'Single Family Units' },
  { column: 'duplex_units', label: 'Duplex Units' },
  { column: 'apartment_units', label: 'Apartment Units' },
  { column: 'mobile_home_units', label: 'Mobile Home Units' },
  { column: 'condo_units', label: 'Condo Units' },
  { column: 'number_of_parking_spaces', label: 'Number of Parking Spaces' },
  { column: 'jea_water_construction_permit_number', label: 'JEA Water Construction Permit #' },
  {
    column: 'jea_wastewater_construction_permit_number',
    label: 'JEA Wastewater Construction Permit #',
  },
  { column: 'jea_water_construction_permit_date', label: 'JEA Water Construction Permit Date' },
  {
    column: 'jea_wastewater_construction_permit_date',
    label: 'JEA Wastewater Construction Permit Date',
  },
  { column: 'contractor_name', label: 'Contractor Name' },
  { column: 'contractor_phone', label: 'Contractor Phone' },
  { column: 'lift_station_address', label: 'Lift Station Address' },
  { column: 'lift_station_meter_number', label: 'Lift Station Meter Number' },
  { column: 'major_access', label: 'Major Access' },
  { column: 'future_land_use', label: 'Future Land Use' },
  { column: 'present_use_of_property', label: 'Present Use of Property' },
  { column: 'building_sqft', label: 'Building SQFT' },
  { column: 'project_description', label: 'Project Description' },
  { column: 'permit_number', label: 'Permit No.' },
  { column: 'section_number', label: 'Section No.' },
  { column: 'state_road', label: 'State Road' },
  { column: 'county', label: 'County' },
  { column: 'government_development_review', label: 'Government Development Review' },
  { column: 'reviewer_name', label: 'Reviewer Name' },
  { column: 'reviewer_phone', label: 'Reviewer Phone' },
  { column: 'reviewer_position', label: 'Reviewer Position' },
  { column: 'business_type', label: 'Business Type' },
  { column: 'commercial_sqft', label: 'Commercial SQFT' },
  { column: 'residential_type', label: 'Residential Type' },
  { column: 'number_of_units', label: 'Number of Units' },
  { column: 'daily_traffic_estimate', label: 'Daily Traffic Estimate' },
  { column: 'ite_land_use_code', label: 'ITE Land Use Code' },
  { column: 'independent_variables', label: 'Independent Variables' },
  { column: 'ite_report_page_reference', label: 'ITE Report page # reference' },
  { column: 'street_name', label: 'Street Name' },
  { column: 'state_road_number', label: 'State Road #' },
  { column: 'us_highway_number', label: 'US Highway #' },
  { column: 'latitude', label: 'Latitude' },
  { column: 'longitude', label: 'Longitude' },
  { column: 'benchmark_hor_datum', label: 'Benchmark Hor Datum' },
  { column: 'state_plane_northing', label: 'State Plane Northing' },
  { column: 'state_plane_easting', label: 'State Plane Easting' },
  { column: 'desc_of_facility_and_connection', label: 'Desc Of Facility and Connection' },
  { column: 'desc_for_needing_permit', label: 'Desc For needing permit' },
] as const

export const PROJECT_INFO_EXTRA_PHONE_COLUMNS = new Set([
  'engineer_phone',
  'owner_phone',
  'contractor_phone',
  'reviewer_phone',
])

export type ProjectInfoGroupedField = {
  label: string
  key: string
}

export const PROJECT_INFO_GROUPS: Array<{ title: string; fields: ProjectInfoGroupedField[] }> = [
  {
    title: 'General',
    fields: [
      { label: 'Project Number', key: 'core.projectNumber' },
      { label: 'Project Name', key: 'core.projectName' },
      { label: 'Project Manager', key: 'core.projectManager' },
      { label: 'Engineer Name', key: 'core.projectEngineer' },
      { label: 'Client', key: 'core.client' },
      { label: 'Developer Address (Line 1)', key: 'core.clientAddressLine1' },
      { label: 'Developer Address (Line 2)', key: 'core.clientAddressLine2' },
      { label: 'Developer Phone', key: 'core.clientPhone' },
      { label: 'Project Date', key: 'core.projectDate' },
      { label: 'Availability #', key: 'core.availabilityNumber' },
      { label: 'City/County', key: 'core.cityCounty' },
      { label: 'PE #', key: 'extra.pe_number' },
      { label: 'Engineer Email', key: 'extra.engineer_email' },
      { label: 'Engineer Phone', key: 'extra.engineer_phone' },
      { label: 'Date', key: 'extra.engineer_date' },
      { label: 'Major Access', key: 'extra.major_access' },
      { label: 'Future Land Use', key: 'extra.future_land_use' },
      { label: 'Present Use of Property', key: 'extra.present_use_of_property' },
      { label: 'Building SQFT', key: 'extra.building_sqft' },
      { label: 'Project Description', key: 'extra.project_description' },
    ],
  },
  {
    title: 'COJ',
    fields: [
      { label: 'Developer Name', key: 'extra.developer_name' },
      { label: 'Owner Name', key: 'extra.owner_name' },
      { label: 'Corporate Title', key: 'extra.corporate_title' },
      { label: 'Owner Address', key: 'extra.owner_address' },
      { label: 'Owner # and Street', key: 'extra.owner_number_and_street' },
      { label: 'Owner City, State, Zip', key: 'extra.owner_city_state_zip' },
      { label: 'Owner City, State', key: 'extra.owner_city_state' },
      { label: 'Owner City', key: 'extra.owner_city' },
      { label: 'Owner State', key: 'extra.owner_state' },
      { label: 'Owner Zip', key: 'extra.owner_zip' },
      { label: 'Owner Email', key: 'extra.owner_email' },
      { label: 'Owner Phone', key: 'extra.owner_phone' },
      { label: 'Project Address', key: 'extra.project_address' },
      { label: 'Project #', key: 'extra.project_ref_number' },
      { label: 'Project # and Street', key: 'extra.project_number_and_street' },
      { label: 'Project City, State, Zip', key: 'extra.project_city_state_zip' },
      { label: 'Project Street, City, State, Zip', key: 'extra.project_street_city_state_zip' },
      { label: 'Section', key: 'extra.section' },
      { label: 'Township', key: 'extra.township' },
      { label: 'Range', key: 'extra.range' },
      { label: 'Between Streets', key: 'extra.between_streets' },
      { label: 'Council District', key: 'extra.council_district' },
      { label: 'Planning District', key: 'extra.planning_district' },
      { label: 'Census Tract', key: 'extra.census_tract' },
      { label: 'Zoning', key: 'extra.zoning' },
      { label: 'PUD Ordinance', key: 'extra.pud_ordinance' },
      { label: 'Mobility Zone', key: 'extra.mobility_zone' },
      { label: 'Panel Number', key: 'extra.panel_number' },
      { label: 'RE Numbers', key: 'extra.re_numbers' },
      { label: 'Transportation Land Use Code', key: 'extra.transportation_land_use_code' },
      { label: 'Previous Land Use Code', key: 'extra.previous_land_use_code' },
      { label: 'Total Land Area', key: 'extra.total_land_area' },
      { label: 'Developed Land Area', key: 'extra.developed_land_area' },
      { label: 'Total Units', key: 'extra.total_units' },
      { label: 'Single Family Units', key: 'extra.single_family_units' },
      { label: 'Duplex Units', key: 'extra.duplex_units' },
      { label: 'Apartment Units', key: 'extra.apartment_units' },
      { label: 'Mobile Home Units', key: 'extra.mobile_home_units' },
      { label: 'Condo Units', key: 'extra.condo_units' },
      { label: 'Number of Parking Spaces', key: 'extra.number_of_parking_spaces' },
    ],
  },
  {
    title: 'JEA',
    fields: [
      {
        label: 'JEA Water Construction Permit #',
        key: 'extra.jea_water_construction_permit_number',
      },
      {
        label: 'JEA Wastewater Construction Permit #',
        key: 'extra.jea_wastewater_construction_permit_number',
      },
      {
        label: 'JEA Water Construction Permit Date',
        key: 'extra.jea_water_construction_permit_date',
      },
      {
        label: 'JEA Wastewater Construction Permit Date',
        key: 'extra.jea_wastewater_construction_permit_date',
      },
      { label: 'Contractor Name', key: 'extra.contractor_name' },
      { label: 'Contractor Phone', key: 'extra.contractor_phone' },
      { label: 'Lift Station Address', key: 'extra.lift_station_address' },
      { label: 'Lift Station Meter Number', key: 'extra.lift_station_meter_number' },
    ],
  },
  {
    title: 'FDOT',
    fields: [
      { label: 'Permit No.', key: 'extra.permit_number' },
      { label: 'Section No.', key: 'extra.section_number' },
      { label: 'State Road', key: 'extra.state_road' },
      { label: 'County', key: 'extra.county' },
      { label: 'Government Development Review', key: 'extra.government_development_review' },
      { label: 'Reviewer Name', key: 'extra.reviewer_name' },
      { label: 'Reviewer Phone', key: 'extra.reviewer_phone' },
      { label: 'Reviewer Position', key: 'extra.reviewer_position' },
      { label: 'Business Type', key: 'extra.business_type' },
      { label: 'Commercial SQFT', key: 'extra.commercial_sqft' },
      { label: 'Residential Type', key: 'extra.residential_type' },
      { label: 'Number of Units', key: 'extra.number_of_units' },
      { label: 'Daily Traffic Estimate', key: 'extra.daily_traffic_estimate' },
      { label: 'ITE Land Use Code', key: 'extra.ite_land_use_code' },
      { label: 'Independent Variables', key: 'extra.independent_variables' },
      { label: 'ITE Report page # reference', key: 'extra.ite_report_page_reference' },
      { label: 'Street Name', key: 'extra.street_name' },
      { label: 'State Road #', key: 'extra.state_road_number' },
      { label: 'US Highway #', key: 'extra.us_highway_number' },
      { label: 'Latitude', key: 'extra.latitude' },
      { label: 'Longitude', key: 'extra.longitude' },
      { label: 'Benchmark Hor Datum', key: 'extra.benchmark_hor_datum' },
      { label: 'State Plane Northing', key: 'extra.state_plane_northing' },
      { label: 'State Plane Easting', key: 'extra.state_plane_easting' },
      {
        label: 'Desc Of Facility and Connection',
        key: 'extra.desc_of_facility_and_connection',
      },
      { label: 'Desc For needing permit', key: 'extra.desc_for_needing_permit' },
    ],
  },
]

export const buildEmptyExtraProjectInfoForm = () =>
  Object.fromEntries(PROJECT_INFO_EXTRA_FIELDS.map((field) => [field.column, ''])) as Record<
    string,
    string
  >
