alter table if exists public.project_info_field_catalog
  add column if not exists value_mode text not null default 'scalar';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'project_info_field_catalog_value_mode_check'
  ) then
    alter table public.project_info_field_catalog
      add constraint project_info_field_catalog_value_mode_check
      check (value_mode in ('scalar', 'multi'));
  end if;
end
$$;

create table if not exists public.project_info_field_values (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  field_id bigint not null references public.project_info_field_catalog(id) on delete cascade,
  value text not null,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_project_info_field_values_project_field_active_sort
  on public.project_info_field_values(project_id, field_id, is_active, sort_order, id);

create unique index if not exists ux_project_info_field_values_project_field_value
  on public.project_info_field_values(project_id, field_id, value)
  where is_active = true;

drop trigger if exists trg_project_info_field_values_updated_at on public.project_info_field_values;
create trigger trg_project_info_field_values_updated_at
before update on public.project_info_field_values
for each row execute function public.set_updated_at_timestamp();
