CREATE TABLE IF NOT EXISTS public.invoice_billables (
  id BIGINT PRIMARY KEY GENERATED BY IDENTITY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  contract_phase_id BIGINT NOT NULL REFERENCES public.contract_phases(id) ON DELETE CASCADE,
  billing_period TEXT NOT NULL, -- format: "2026-03"

  -- For hourly phases: calculated value (hours × billable_rate)
  calculated_billable NUMERIC(14,2),

  -- For lump-sum phases: PM manually enters this value
  -- For hourly: if PM wants to override, they can set this
  manual_override_amount NUMERIC(14,2),

  -- Final amount that will be billed (either manual_override or calculated)
  final_billable_amount NUMERIC(14,2) GENERATED ALWAYS AS (
    COALESCE(manual_override_amount, calculated_billable)
  ) STORED,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(project_id, contract_phase_id, billing_period)
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS ix_invoice_billables_project_id
  ON public.invoice_billables(project_id);
CREATE INDEX IF NOT EXISTS ix_invoice_billables_contract_phase_id
  ON public.invoice_billables(contract_phase_id);
CREATE INDEX IF NOT EXISTS ix_invoice_billables_period
  ON public.invoice_billables(billing_period);
CREATE INDEX IF NOT EXISTS ix_invoice_billables_project_period
  ON public.invoice_billables(project_id, billing_period);

-- Enable RLS
ALTER TABLE public.invoice_billables ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Admin full access
CREATE POLICY "invoice_billables_admin_full" ON public.invoice_billables
  AS PERMISSIVE FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- RLS Policy: Project Managers can manage billables for their projects
CREATE POLICY "invoice_billables_pm_own_projects" ON public.invoice_billables
  AS PERMISSIVE FOR ALL USING (
    project_id IN (
      SELECT p.id FROM public.projects p
      WHERE p.pm_id = auth.uid()
        OR p.id IN (
          SELECT project_id FROM public.project_team_assignments
          WHERE user_id = auth.uid()
        )
    )
  );
