CREATE TABLE IF NOT EXISTS public.project_team_assignments (
  id BIGINT PRIMARY KEY GENERATED BY IDENTITY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'team_member', -- 'project_manager' or 'team_member'
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(project_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_project_team_project_id 
  ON public.project_team_assignments(project_id);
CREATE INDEX IF NOT EXISTS ix_project_team_user_id 
  ON public.project_team_assignments(user_id);
CREATE INDEX IF NOT EXISTS ix_project_team_user_role 
  ON public.project_team_assignments(user_id, role);

ALTER TABLE public.project_team_assignments ENABLE ROW LEVEL SECURITY;

-- Admin full access
CREATE POLICY "project_team_admin_full" ON public.project_team_assignments
  AS PERMISSIVE FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- Users can see assignments for projects they're on
CREATE POLICY "project_team_see_own" ON public.project_team_assignments
  AS PERMISSIVE FOR SELECT USING (
    project_id IN (
      SELECT id FROM public.projects WHERE pm_id = auth.uid()
      UNION
      SELECT project_id FROM public.project_team_assignments WHERE user_id = auth.uid()
    )
  );

-- PMs and admin can modify
CREATE POLICY "project_team_pm_modify" ON public.project_team_assignments
  AS PERMISSIVE FOR INSERT WITH CHECK (
    project_id IN (
      SELECT id FROM public.projects WHERE pm_id = auth.uid()
    )
    OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

CREATE POLICY "project_team_pm_update" ON public.project_team_assignments
  AS PERMISSIVE FOR UPDATE USING (
    project_id IN (
      SELECT id FROM public.projects WHERE pm_id = auth.uid()
    )
    OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

CREATE POLICY "project_team_pm_delete" ON public.project_team_assignments
  AS PERMISSIVE FOR DELETE USING (
    project_id IN (
      SELECT id FROM public.projects WHERE pm_id = auth.uid()
    )
    OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );
